# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaiduMapPOI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaiduMapPOI

  target 'BaiduMapPOITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaiduMapPOIUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'BaiduMapKit'
end
